// resources/js/Pages/Panel/MedicalRecords/Index.vue
<script setup>
import { ref, computed, onMounted } from 'vue';
import { router, Link } from '@inertiajs/vue3';
import AppLayout            from '@/Layouts/AppLayout.vue';
import PageHeader           from '@/Components/Panel/PageHeader.vue';
import ActionIconGroup      from '@/Components/Panel/ActionIconGroup.vue';
import ActionIconButton     from '@/Components/Panel/ActionIconButton.vue';
import ActionDropdown       from '@/Components/Panel/ActionDropdown.vue';
import MedicalRecordDetailDrawer from './MedicalRecordDetailDrawer.vue';
import PatientInfoSidebar   from './Components/PatientInfoSidebar.vue';
import PdfPreviewModal      from './Components/PdfPreviewModal.vue';

const props = defineProps({
    breadcrumbs: { type: Array,  default: () => [] },
    patient:     { type: Object, required: true },
    urls:        { type: Object, required: true },
    t:           { type: Object, default: () => ({}) },
    /** Apenas médicos podem criar/editar prontuário (CFM Res. 2.227/2018). */
    isDoctor:    { type: Boolean, default: false },
});

// ── Timeline: paginação infinita ────────────────────────────────────────────
const records      = ref([]);
const loading      = ref(false);
const loadingMore  = ref(false);
const hasMore      = ref(true);
const nextPage     = ref(1);
const total        = ref(0);

async function loadPage(page = 1) {
    if (page === 1) {
        loading.value = true;
        records.value = [];
    } else {
        loadingMore.value = true;
    }

    try {
        const res  = await fetch(`${props.urls.ajax_list}?page=${page}&per_page=10`, {
            headers: { Accept: 'application/json' },
        });
        const json = await res.json();

        if (page === 1) records.value = json.data;
        else            records.value.push(...json.data);

        hasMore.value  = json.has_more;
        nextPage.value = json.next_page;
        total.value    = json.total;
    } finally {
        loading.value     = false;
        loadingMore.value = false;
    }
}

onMounted(() => loadPage(1));

// ── Detail drawer ───────────────────────────────────────────────────────────
const detailOpen   = ref(false);
const detailRecord = ref(null);

function openDetail(record) {
    detailRecord.value = record;
    detailOpen.value   = true;
}

// ── PDF preview modal ───────────────────────────────────────────────────────
// Em vez de abrir o PDF direto em nova aba (download bruto), exibimos primeiro
// num iframe dentro de um modal com opção de baixar/abrir externamente.
const pdfPreviewOpen  = ref(false);
const pdfPreviewUrl   = ref('');
const pdfPreviewTitle = ref('');

function openPdfPreview(record) {
    if (!record?.pdf_url) return;
    pdfPreviewUrl.value   = record.pdf_url;
    pdfPreviewTitle.value = `Prontuário ${record.code} — ${record.created_at ?? ''}`;
    pdfPreviewOpen.value  = true;
}

function closePdfPreview() {
    pdfPreviewOpen.value  = false;
    pdfPreviewUrl.value   = '';
    pdfPreviewTitle.value = '';
}

// ── Delete ──────────────────────────────────────────────────────────────────
async function onDelete(record) {
    if (record.is_locked) {
        alert('Prontuário assinado/bloqueado — não pode ser excluído.');
        return;
    }
    if (!confirm('Excluir este prontuário?')) return;

    const res = await fetch(record.destroy_url, {
        method: 'DELETE',
        headers: {
            'Accept':       'application/json',
            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.content ?? '',
        },
    });

    if (res.ok || res.status === 302) {
        if (window.showSuccessToast) window.showSuccessToast('Prontuário removido.');
        loadPage(1);
    } else if (window.showErrorToast) {
        window.showErrorToast('Erro ao remover.');
    }
}

const isEmpty = computed(() => !loading.value && records.value.length === 0);
</script>

<template>
    <AppLayout :title="t.title ?? 'Prontuários'" :breadcrumbs="breadcrumbs">
        <div class="container-fluid py-3 page-medical-records">

            <!-- Header ocupa a linha toda (padrão das telas raiz do painel) -->
            <PageHeader
                :title="`${patient.full_name ?? 'Paciente'} — ${t.title ?? 'Prontuários'}`"
                :total="total > 0 ? total : null"
            >
                <template #actions>
                    <div class="btn-group" role="group">
                        <Link :href="urls.patients" class="btn btn-outline-secondary btn-sm">
                            <i class="ti ti-arrow-left me-1"></i>Pacientes
                        </Link>
                        <!-- Novo prontuário: exclusivo para médicos (CFM 2.227/2018). -->
                        <Link v-if="isDoctor" :href="urls.create" class="btn btn-primary btn-sm">
                            <i class="ti ti-plus me-1"></i>Novo prontuário
                        </Link>
                    </div>
                </template>
            </PageHeader>

            <div class="row g-3">
                <!-- Coluna lateral: info do paciente (componente padrão do prontuário) -->
                <div class="col-12 col-md-3 col-lg-2">
                    <div class="patient-info-sticky">
                        <PatientInfoSidebar :patient="patient" />
                    </div>
                </div>

                <!-- Coluna principal: timeline -->
                <div class="col-12 col-md-9 col-lg-10">

                    <div class="card">
                        <div class="card-body">
                            <!-- Loading -->
                            <div v-if="loading" class="text-center py-5">
                                <div class="spinner-border text-info"></div>
                            </div>

                            <!-- Empty -->
                            <div v-else-if="isEmpty" class="text-center py-5 text-muted">
                                <i class="ti ti-file-text-ai fs-1 d-block mb-3 opacity-25"></i>
                                <p class="mb-3">{{ t.no_records ?? 'Nenhum prontuário cadastrado.' }}</p>
                                <Link v-if="isDoctor" :href="urls.create" class="btn btn-primary btn-sm">
                                    <i class="ti ti-plus me-1"></i>Criar primeiro prontuário
                                </Link>
                            </div>

                            <!-- Timeline -->
                            <div v-else class="medical-record-timeline">
                                <div
                                    v-for="record in records"
                                    :key="record.id"
                                    class="timeline-item"
                                >
                                    <div class="d-flex gap-3">
                                        <div class="timeline-marker">
                                            <i :class="`ti ${record.is_signed ? 'ti-shield-check-filled text-success' : 'ti-file-text text-info'} fs-4`"></i>
                                        </div>
                                        <div class="flex-grow-1 timeline-content">
                                            <div class="card border-0 shadow-sm">
                                                <div class="card-body">
                                                    <div class="d-flex justify-content-between align-items-start mb-2">
                                                        <div>
                                                            <h6 class="mb-0 fw-semibold">
                                                                <code class="small text-muted me-2">{{ record.code }}</code>
                                                                {{ record.created_at }}
                                                            </h6>
                                                            <small v-if="record.doctor_name" class="text-muted">
                                                                <i class="ti ti-stethoscope me-1"></i>{{ record.doctor_name }}
                                                            </small>
                                                        </div>
                                                        <div class="d-flex gap-1">
                                                            <span v-if="record.is_signed"
                                                                  class="badge badge-soft-success rounded text-success border border-success fs-11"
                                                                  :title="`Assinado em ${record.signed_at}`">
                                                                <i class="ti ti-shield-check me-1"></i>Assinado
                                                            </span>
                                                            <span v-if="record.documentations_count > 0"
                                                                  class="badge badge-soft-info rounded fs-11">
                                                                <i class="ti ti-paperclip me-1"></i>{{ record.documentations_count }} doc(s)
                                                            </span>
                                                        </div>
                                                    </div>

                                                    <div v-if="record.main_complaint" class="mb-2 small">
                                                        <strong class="text-muted">Queixa:</strong>
                                                        {{ record.main_complaint }}
                                                    </div>

                                                    <div v-if="record.clinical_conduct" class="mb-2 small">
                                                        <strong class="text-muted">Conduta:</strong>
                                                        {{ record.clinical_conduct }}
                                                    </div>

                                                    <div v-if="record.diagnosis_cids?.length > 0" class="mb-2">
                                                        <span v-for="(cid, idx) in record.diagnosis_cids" :key="idx"
                                                              class="badge badge-soft-secondary me-1 fs-11">
                                                            {{ typeof cid === 'object' ? `${cid.code} ${cid.description ?? ''}` : cid }}
                                                        </span>
                                                    </div>

                                                    <!--
                                                        Ações:
                                                          - Ver detalhes: aberto a todos os perfis (read-only)
                                                          - Editar: exclusivo para médicos (CFM 2.227/2018). Admin/secretária
                                                            não vê o botão. Se locked (assinado), nem médico edita.
                                                          - Visualizar PDF: aberto a todos
                                                          - Excluir: exclusivo para médicos + não-locked
                                                    -->
                                                    <div class="d-flex justify-content-end mt-3">
                                                        <ActionIconGroup align="end" gap="tight">
                                                            <ActionIconButton
                                                                icon="ti ti-eye"
                                                                title="Ver detalhes"
                                                                variant="default"
                                                                @click="openDetail(record)"
                                                            />
                                                            <ActionIconButton
                                                                v-if="isDoctor"
                                                                :icon="record.is_locked ? 'ti ti-lock' : 'ti ti-edit'"
                                                                :title="record.is_locked ? 'Visualizar (assinado)' : 'Editar prontuário'"
                                                                :href="record.edit_url"
                                                                variant="default"
                                                            />
                                                            <ActionDropdown
                                                                btn-class="ee-action-icon ee-action-icon--default"
                                                                icon="ti ti-dots-vertical"
                                                                align="right"
                                                            >
                                                                <li>
                                                                    <button type="button" class="dropdown-item" @click="openPdfPreview(record)">
                                                                        <i class="ti ti-file-search me-2 text-secondary"></i>Visualizar PDF
                                                                    </button>
                                                                </li>
                                                                <li v-if="isDoctor && !record.is_locked"><hr class="dropdown-divider"></li>
                                                                <li v-if="isDoctor && !record.is_locked">
                                                                    <button type="button" class="dropdown-item text-danger" @click="onDelete(record)">
                                                                        <i class="ti ti-trash me-2"></i>Excluir
                                                                    </button>
                                                                </li>
                                                            </ActionDropdown>
                                                        </ActionIconGroup>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!-- Load more -->
                                <div v-if="hasMore" class="text-center py-3">
                                    <button class="btn btn-outline-secondary btn-sm" :disabled="loadingMore" @click="loadPage(nextPage)">
                                        <span v-if="loadingMore" class="spinner-border spinner-border-sm me-1"></span>
                                        <i v-else class="ti ti-chevron-down me-1"></i>
                                        Carregar mais
                                    </button>
                                </div>

                                <div v-else-if="!isEmpty" class="text-center py-3 text-muted small">
                                    <i class="ti ti-check me-1 text-success"></i>Fim da lista
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <MedicalRecordDetailDrawer
                :open="detailOpen"
                :record="detailRecord"
                :patient="patient"
                @close="detailOpen = false"
            />

            <!-- PDF preview universal: abre dentro de modal antes de baixar -->
            <PdfPreviewModal
                v-if="pdfPreviewOpen"
                :url="pdfPreviewUrl"
                :title="pdfPreviewTitle"
                :filename="`prontuario-${patient.code ?? 'paciente'}`"
                @close="closePdfPreview"
            />
        </div>
    </AppLayout>
</template>

<style scoped>
.patient-info-sticky { position: sticky; top: 1rem; }
.medical-record-timeline { position: relative; padding-left: 1rem; }
.timeline-item { position: relative; margin-bottom: 1rem; padding-bottom: 1rem; border-left: 2px solid var(--bs-border-color); padding-left: 1rem; }
.timeline-item:last-child { border-left-color: transparent; }
.timeline-marker {
    position: absolute;
    left: -22px;
    top: 12px;
    width: 40px;
    height: 40px;
    background: white;
    border: 2px solid var(--bs-border-color);
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
}
</style>

// resources/js/Pages/MedicalRecords/Index.jsx
import { useState, useEffect, useCallback } from 'react';
import { Link } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import FlashMessages from '@/Components/UI/FlashMessages';
import PageHeader from '@/Components/UI/PageHeader';
import Modal from '@/Components/UI/Modal';
import Badge from '@/Components/UI/Badge';

export default function MedicalRecordsIndex({ patient }) {
    const [records, setRecords] = useState([]);
    const [page, setPage] = useState(1);
    const [hasMore, setHasMore] = useState(false);
    const [total, setTotal] = useState(0);
    const [loading, setLoading] = useState(true);
    const [detailRecord, setDetailRecord] = useState(null);
    const [showDetail, setShowDetail] = useState(false);

    const person = patient.person;

    const fetchRecords = useCallback(async (p = 1, append = false) => {
        setLoading(true);
        try {
            const res = await fetch(`/panel/patients/${patient.id}/medicalrecords/ajaxlist?per_page=10&page=${p}`, {
                headers: { 'Accept': 'application/json', 'X-Requested-With': 'XMLHttpRequest' },
            });
            const json = await res.json();
            setTotal(json.total || 0);
            setHasMore(json.has_more || false);

            if (append) {
                setRecords((prev) => [...prev, ...(json.data || [])]);
            } else {
                setRecords(json.data || []);
            }
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    }, [patient.id]);

    useEffect(() => {
        fetchRecords();
    }, [fetchRecords]);

    const loadMore = () => {
        const nextPage = page + 1;
        setPage(nextPage);
        fetchRecords(nextPage, true);
    };

    const viewDetail = async (recordId) => {
        try {
            const res = await fetch(`/panel/patients/${patient.id}/medicalrecords/${recordId}`, {
                headers: { 'Accept': 'application/json', 'X-Requested-With': 'XMLHttpRequest' },
            });
            const json = await res.json();
            setDetailRecord(json);
            setShowDetail(true);
        } catch { /* ignore */ }
    };

    return (
        <AuthenticatedLayout title={`Prontuários — ${person?.full_name || patient.code}`}>
            <FlashMessages />

            <nav aria-label="breadcrumb" className="mb-3">
                <ol className="breadcrumb mb-0">
                    <li className="breadcrumb-item"><Link href="/panel/dashboard">Dashboard</Link></li>
                    <li className="breadcrumb-item"><Link href="/panel/patients">Pacientes</Link></li>
                    <li className="breadcrumb-item"><Link href={`/panel/patients/${patient.id}`}>{person?.full_name || patient.code}</Link></li>
                    <li className="breadcrumb-item active">Prontuários</li>
                </ol>
            </nav>

            {/* Patient Info Card */}
            <div className="card border-0 shadow-sm mb-3">
                <div className="card-body d-flex align-items-center gap-3 py-2">
                    <img src="/system/images/team.png" className="rounded-circle" width="48" height="48" alt="" />
                    <div>
                        <h6 className="mb-0 fw-semibold">{person?.full_name}</h6>
                        <span className="text-muted small">
                            <code>{patient.code}</code>
                            {patient.covenant?.name && <span className="ms-2">· {patient.covenant.name}</span>}
                        </span>
                    </div>
                    <div className="ms-auto">
                        <Link href={`/panel/patients/${patient.id}/medicalrecords/create`} className="btn btn-primary btn-sm">
                            <i className="ti ti-plus me-1"></i> Novo Prontuário
                        </Link>
                    </div>
                </div>
            </div>

            <PageHeader title="Prontuários" subtitle={`${total} registro${total !== 1 ? 's' : ''}`} />

            {/* Timeline */}
            {loading && page === 1 ? (
                <div className="text-center py-5">
                    <div className="spinner-border text-primary"><span className="visually-hidden">Carregando...</span></div>
                </div>
            ) : records.length > 0 ? (
                <>
                    <ul className="timeline">
                        {records.map((record, i) => {
                            const inverted = i % 2 !== 0;
                            const hasFlags = record.diabetic || record.hypertensive || record.glaucomatous;

                            return (
                                <li key={record.id} className={inverted ? 'timeline-inverted' : ''}>
                                    <div className="timeline-badge" style={{ backgroundColor: record.doctor_color }}>
                                        <img src={record.doctor_photo} alt={record.doctor_name} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                                    </div>
                                    <div className="timeline-panel">
                                        <div className="timeline-heading">
                                            <h5 className="timeline-title mb-1" style={{ color: record.doctor_color }}>
                                                {record.doctor_name}
                                            </h5>
                                            <p className="text-muted small mb-2">
                                                <i className="ti ti-clock me-1"></i>
                                                {record.created_at_formatted} &mdash; <span className="text-secondary fw-semibold">{record.code}</span>
                                            </p>
                                            
                                            {hasFlags && (
                                                <div className="mb-2">
                                                    {record.diabetic && <span className="badge bg-warning text-dark me-1"><i className="ti ti-droplet me-1"></i> Diabético</span>}
                                                    {record.hypertensive && <span className="badge bg-danger text-white me-1"><i className="ti ti-heart-rate-monitor me-1"></i> Hipertenso</span>}
                                                    {record.glaucomatous && <span className="badge bg-info text-white me-1"><i className="ti ti-eye me-1"></i> Glaucoma</span>}
                                                </div>
                                            )}
                                        </div>
                                        <div className="timeline-body">
                                            {record.main_complaint && (
                                                <p className="text-muted small mb-2">{record.main_complaint}</p>
                                            )}
                                            
                                            {(record.tonometer_right || record.tonometer_left) && (
                                                <p className="small mb-2 text-secondary">
                                                    <i className="ti ti-ruler-measure me-1"></i>
                                                    <strong>OD:</strong> {record.tonometer_right || '—'} &nbsp;
                                                    <strong>OE:</strong> {record.tonometer_left || '—'}
                                                </p>
                                            )}

                                            <div className={`mt-2 ${inverted ? 'text-start' : 'text-end'}`}>
                                                <button type="button" className="btn btn-outline-secondary btn-sm me-1" onClick={() => viewDetail(record.id)} title="Ver Detalhes">
                                                    <i className="ti ti-eye"></i>
                                                </button>
                                                <Link href={`/panel/patients/${patient.id}/medicalrecords/${record.id}/edit`} className="btn btn-outline-secondary btn-sm" title="Editar">
                                                    <i className="ti ti-pencil"></i>
                                                </Link>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            );
                        })}
                    </ul>
                    {hasMore && (
                        <div className="text-center mt-3">
                            <button className="btn btn-outline-primary btn-sm" onClick={loadMore} disabled={loading}>
                                {loading ? 'Carregando...' : 'Carregar mais'}
                            </button>
                        </div>
                    )}
                </>
            ) : (
                <div className="text-center text-muted py-5">
                    <i className="ti ti-file-medical fs-1 d-block mb-2"></i>
                    Nenhum prontuário registrado para este paciente.
                </div>
            )}

            {/* Detail Modal */}
            <Modal show={showDetail} onClose={() => setShowDetail(false)} title={`Prontuário ${detailRecord?.code || ''}`} size="lg">
                {detailRecord && (
                    <div>
                        <div className="row">
                            <div className="col-md-6"><InfoRow label="Data" value={detailRecord.created_at_formatted} /></div>
                            <div className="col-md-6"><InfoRow label="Médico" value={detailRecord.doctor_name} /></div>
                        </div>
                        <hr />
                        <InfoRow label={detailRecord.labels?.complaint || 'Queixa Principal'} value={detailRecord.main_complaint} />

                        <h6 className="fw-semibold mt-3 mb-2">{detailRecord.labels?.history || 'Histórico'}</h6>
                        <div className="row">
                            <div className="col-md-4">
                                <HistoryItem label={detailRecord.labels?.diabetic} value={detailRecord.diabetic} family={detailRecord.diabetic_family} labels={detailRecord.labels} />
                            </div>
                            <div className="col-md-4">
                                <HistoryItem label={detailRecord.labels?.hypertensive} value={detailRecord.hypertensive} family={detailRecord.hypertensive_family} labels={detailRecord.labels} />
                            </div>
                            <div className="col-md-4">
                                <HistoryItem label={detailRecord.labels?.glaucomatous} value={detailRecord.glaucomatous} family={detailRecord.glaucomatous_family} labels={detailRecord.labels} />
                            </div>
                        </div>

                        {(detailRecord.tonometer_right || detailRecord.tonometer_left) && (
                            <>
                                <h6 className="fw-semibold mt-3 mb-2">{detailRecord.labels?.tonometry || 'Tonometria'}</h6>
                                <div className="row">
                                    <div className="col-md-4"><InfoRow label="OD" value={detailRecord.tonometer_right} /></div>
                                    <div className="col-md-4"><InfoRow label="OE" value={detailRecord.tonometer_left} /></div>
                                    <div className="col-md-4"><InfoRow label="Horário" value={detailRecord.tonometer_time} /></div>
                                </div>
                            </>
                        )}

                        {detailRecord.observation_general && (
                            <InfoRow label={detailRecord.labels?.general_obs || 'Observações Gerais'} value={detailRecord.observation_general} />
                        )}
                        {detailRecord.observation_of_lenses && (
                            <InfoRow label={detailRecord.labels?.lenses_obs || 'Observações de Lentes'} value={detailRecord.observation_of_lenses} />
                        )}
                    </div>
                )}
            </Modal>
        </AuthenticatedLayout>
    );
}

function InfoRow({ label, value }) {
    return (
        <div className="mb-2">
            <span className="text-muted small d-block">{label}</span>
            <span className="fw-medium">{value || '—'}</span>
        </div>
    );
}

function HistoryItem({ label, value, family, labels }) {
    const yes = labels?.yes || 'Sim';
    const no = labels?.no || 'Não';
    const familyLabel = labels?.family || 'Familiar';

    return (
        <div className="mb-2">
            <span className="fw-medium d-block">{label}</span>
            <Badge variant={value ? 'warning' : 'success'}>{value ? yes : no}</Badge>
            <span className="text-muted small ms-2">{familyLabel}: {family ? yes : no}</span>
        </div>
    );
}
