// resources/js/Pages/Auth/ResetPassword.jsx
import { useState } from 'react';
import { router, usePage } from '@inertiajs/react';
import GuestLayout from '@/Layouts/GuestLayout';

export default function ResetPassword({ token, email }) {
    const { errors } = usePage().props;
    const [form, setForm] = useState({
        token, email: email || '', password: '', password_confirmation: '',
    });
    const [processing, setProcessing] = useState(false);

    const handleSubmit = (e) => {
        e.preventDefault();
        setProcessing(true);
        router.post('/reset-password', form, {
            onFinish: () => setProcessing(false),
        });
    };

    return (
        <GuestLayout title="Redefinir Senha">
            <h2 className="fw-bold mb-1">Redefinir Senha</h2>
            <p className="text-muted mb-4">Digite sua nova senha.</p>

            <form onSubmit={handleSubmit}>
                <div className="mb-3">
                    <label className="form-label">E-mail</label>
                    <input
                        type="email"
                        className={`form-control${errors?.email ? ' is-invalid' : ''}`}
                        value={form.email}
                        onChange={(e) => setForm({ ...form, email: e.target.value })}
                        required
                    />
                    {errors?.email && <div className="invalid-feedback">{errors.email}</div>}
                </div>

                <div className="mb-3">
                    <label className="form-label">Nova Senha</label>
                    <input
                        type="password"
                        className={`form-control${errors?.password ? ' is-invalid' : ''}`}
                        value={form.password}
                        onChange={(e) => setForm({ ...form, password: e.target.value })}
                        autoFocus
                        required
                    />
                    {errors?.password && <div className="invalid-feedback">{errors.password}</div>}
                </div>

                <div className="mb-3">
                    <label className="form-label">Confirmar Nova Senha</label>
                    <input
                        type="password"
                        className="form-control"
                        value={form.password_confirmation}
                        onChange={(e) => setForm({ ...form, password_confirmation: e.target.value })}
                        required
                    />
                </div>

                <button type="submit" className="btn btn-primary w-100" disabled={processing}>
                    {processing ? <><span className="spinner-border spinner-border-sm me-1"></span> Salvando...</> : 'Redefinir Senha'}
                </button>
            </form>
        </GuestLayout>
    );
}

// resources/js/Pages/Auth/ResetPassword.vue
<script setup>
import { Head, useForm } from '@inertiajs/vue3';
import { ref } from 'vue';
import GuestLayout from '@/Layouts/GuestLayout.vue';
import resetIllustrationImg from '@img/system/auth/reset-illustration-img.png';

const props = defineProps({
    appName: { type: String, default: 'EasyEye' },
    t: { type: Object, default: () => ({}) },
    token: { type: String, required: true },
    email: { type: String, default: '' },
});

const showPassword = ref(false);
const showConfirm = ref(false);

const form = useForm({
    token: props.token,
    email: props.email,
    password: '',
    password_confirmation: '',
});

function submit() {
    form.post('/reset-password', {
        onFinish: () => form.reset('password', 'password_confirmation'),
    });
}
</script>

<template>
    <Head :title="t.reset_password?.title" />

    <GuestLayout
        :app-name="appName"
        :title="t.reset_password?.title"
        :illustration-src="resetIllustrationImg"
    >
        <div v-if="form.errors.email" class="alert alert-danger mb-3 py-2">
            <i class="ti ti-alert-circle me-1"></i> {{ form.errors.email }}
        </div>

        <form @submit.prevent="submit" novalidate>
            <input type="hidden" :value="form.token" name="token">

            <div class="mb-3">
                <label class="form-label">{{ t.reset_password?.email }} <span style="color:#ef4444;">*</span></label>
                <div class="input-group">
                    <span class="input-group-text"><i class="ti ti-mail"></i></span>
                    <input
                        v-model="form.email"
                        type="email"
                        class="form-control"
                        :class="{ 'is-invalid': form.errors.email }"
                        autofocus
                        autocomplete="username"
                        required
                    >
                </div>
            </div>

            <div class="mb-3">
                <label class="form-label">{{ t.reset_password?.password }} <span style="color:#ef4444;">*</span></label>
                <div class="input-group">
                    <input
                        v-model="form.password"
                        :type="showPassword ? 'text' : 'password'"
                        class="form-control"
                        :class="{ 'is-invalid': form.errors.password }"
                        autocomplete="new-password"
                        required
                    >
                    <button type="button" class="btn btn-outline-secondary" tabindex="-1" @click="showPassword = !showPassword">
                        <i :class="showPassword ? 'ti ti-eye-off' : 'ti ti-eye'"></i>
                    </button>
                </div>
                <div v-if="form.errors.password" class="invalid-feedback d-block mt-1">{{ form.errors.password }}</div>
            </div>

            <div class="mb-4">
                <label class="form-label">{{ t.reset_password?.confirm_password }} <span style="color:#ef4444;">*</span></label>
                <div class="input-group">
                    <input
                        v-model="form.password_confirmation"
                        :type="showConfirm ? 'text' : 'password'"
                        class="form-control"
                        :class="{ 'is-invalid': form.errors.password_confirmation }"
                        autocomplete="new-password"
                        required
                    >
                    <button type="button" class="btn btn-outline-secondary" tabindex="-1" @click="showConfirm = !showConfirm">
                        <i :class="showConfirm ? 'ti ti-eye-off' : 'ti ti-eye'"></i>
                    </button>
                </div>
            </div>

            <div class="d-grid mb-3">
                <button type="submit" class="btn btn-primary fw-semibold" :disabled="form.processing">
                    <i v-if="form.processing" class="ti ti-loader-2 ee-spin me-1"></i>
                    {{ t.reset_password?.submit }}
                </button>
            </div>

            <p class="text-center mb-0">
                <a href="/login" class="text-muted" style="font-size:.875rem; text-decoration:none;">{{ t.back_to_login }}</a>
            </p>
        </form>
    </GuestLayout>
</template>
