// resources/js/Pages/Auth/SelectEntity.vue
<script setup>
import { Head, useForm } from '@inertiajs/vue3';
import GuestLayout from '@/Layouts/GuestLayout.vue';

const props = defineProps({
    appName: { type: String, default: 'EasyEye' },
    t: { type: Object, default: () => ({}) },
    entities: { type: Object, default: () => ({}) },
});

const form = useForm({ entity_user_id: '' });
const logoutForm = useForm({});

function submit() {
    form.post('/select-entity');
}

function logout() {
    logoutForm.post('/logout');
}
</script>

<template>
    <Head :title="t.select_entity" />

    <GuestLayout
        :app-name="appName"
        :title="t.select_entity"
        subtitle="Selecione a clínica para continuar"
        :illustration-src="'/system/images/auth/twostep-verification-illustration-img.png'"
    >
        <div v-if="form.errors.entity_user_id" class="alert alert-danger mb-4">
            {{ form.errors.entity_user_id }}
        </div>

        <form @submit.prevent="submit" novalidate>
            <div class="mb-4">
                <label class="form-label">{{ t.select_entity }} <span style="color:#ef4444;">*</span></label>
                <select
                    v-model="form.entity_user_id"
                    class="form-select"
                    :class="{ 'is-invalid': form.errors.entity_user_id }"
                    required
                >
                    <option value="">Selecione...</option>
                    <option v-for="(name, id) in entities" :key="id" :value="id">{{ name }}</option>
                </select>
            </div>

            <div class="d-grid mb-3">
                <button type="submit" class="btn btn-primary fw-semibold" :disabled="form.processing">
                    <i v-if="form.processing" class="ti ti-loader-2 ee-spin me-1"></i>
                    Selecionar
                </button>
            </div>
        </form>

        <div class="text-center">
            <button
                type="button"
                class="btn btn-link text-muted"
                style="font-size:.875rem;"
                :disabled="logoutForm.processing"
                @click="logout"
            >
                {{ t.log_out }}
            </button>
        </div>
    </GuestLayout>
</template>

// resources/js/Pages/Auth/SelectEntity.jsx
import { useState } from 'react';
import { router, usePage } from '@inertiajs/react';
import GuestLayout from '@/Layouts/GuestLayout';

export default function SelectEntity({ entities }) {
    const { errors } = usePage().props;
    const [selected, setSelected] = useState('');
    const [processing, setProcessing] = useState(false);

    const handleSubmit = (e) => {
        e.preventDefault();
        setProcessing(true);
        router.post('/select-entity', { entity_user_id: selected }, {
            onFinish: () => setProcessing(false),
        });
    };

    return (
        <GuestLayout title="Selecionar Clínica">
            <h2 className="fw-bold mb-1">Selecione a Clínica</h2>
            <p className="text-muted mb-4">Você tem acesso a mais de uma clínica. Escolha em qual deseja operar.</p>

            {errors?.entity_user_id && (
                <div className="alert alert-danger py-2 small">{errors.entity_user_id}</div>
            )}

            <form onSubmit={handleSubmit}>
                <div className="list-group mb-4">
                    {entities.map((entity) => (
                        <label
                            key={entity.id}
                            className={`list-group-item list-group-item-action d-flex align-items-center gap-3 ${selected === entity.id ? 'active' : ''}`}
                            style={{ cursor: 'pointer' }}
                        >
                            <input
                                type="radio"
                                name="entity_user_id"
                                value={entity.id}
                                checked={selected === entity.id}
                                onChange={() => setSelected(entity.id)}
                                className="form-check-input mt-0"
                            />
                            <div>
                                <strong>{entity.entity_name || entity.name}</strong>
                                {entity.code && <span className="d-block text-muted small">{entity.code}</span>}
                                {entity.rule_label && <span className="badge bg-info-light text-info ms-2">{entity.rule_label}</span>}
                            </div>
                        </label>
                    ))}
                </div>

                <button type="submit" className="btn btn-primary w-100" disabled={processing || !selected}>
                    {processing ? <><span className="spinner-border spinner-border-sm me-1"></span> Entrando...</> : 'Continuar'}
                </button>
            </form>
        </GuestLayout>
    );
}
